mode: client
common:
  data_dir: /node/data
  log:
    format: JSON
    level:
      default: info
      cometbft: info
      cometbft/context: error

p2p:
  port: 26657

genesis:
  file: /node/etc/genesis.json

# Registration configuration
registration:
  entity: /home/claude/entity_working.json